"use client";

import "leaflet/dist/leaflet.css";
import { useState } from "react";
import { MapContainer, Polyline, TileLayer } from "react-leaflet";
import { requestRoute, RouteResult } from "@/lib/routing";

export default function Directions({ destination }: { destination: { latitude: number; longitude: number } }) {
  const [origin, setOrigin] = useState({ latitude: "", longitude: "" }); const [mode, setMode] = useState("driving"); const [route, setRoute] = useState<RouteResult | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); const latitude = Number(origin.latitude); const longitude = Number(origin.longitude); if (!Number.isFinite(latitude) || latitude < -90 || latitude > 90 || !Number.isFinite(longitude) || longitude < -180 || longitude > 180) { setError("Enter a valid origin latitude and longitude."); return; } setLoading(true); try { setRoute(await requestRoute({ origin: { latitude, longitude }, destination, mode })); } catch (err) { setError(err instanceof Error ? err.message : "Route unavailable"); } finally { setLoading(false); } }
  const line = route?.geometry.coordinates.map(([longitude, latitude]) => [latitude, longitude] as [number, number]);
  return <section className="mt-8 rounded-3xl border border-[var(--border)] bg-[var(--card)] p-6 md:p-8"><div className="mb-5"><p className="text-sm font-semibold uppercase tracking-wide text-[var(--primary)]">Directions</p><h2 className="mt-1 text-2xl font-black text-[var(--foreground)]">Get there</h2><p className="mt-2 text-sm text-[var(--muted)]">Use a real OSRM route from any coordinate to this place.</p></div><form onSubmit={submit} className="grid gap-3 md:grid-cols-[1fr_1fr_180px_auto]"><input required inputMode="decimal" placeholder="Origin latitude" value={origin.latitude} onChange={(e) => setOrigin({ ...origin, latitude: e.target.value })} className="rounded-xl border border-[var(--border)] bg-transparent px-3 py-2 text-sm" /><input required inputMode="decimal" placeholder="Origin longitude" value={origin.longitude} onChange={(e) => setOrigin({ ...origin, longitude: e.target.value })} className="rounded-xl border border-[var(--border)] bg-transparent px-3 py-2 text-sm" /><select value={mode} onChange={(e) => setMode(e.target.value)} className="rounded-xl border border-[var(--border)] bg-transparent px-3 py-2 text-sm"><option value="driving">Driving</option><option value="cycling">Cycling</option><option value="walking">Walking (unavailable)</option></select><button disabled={loading} className="rounded-xl bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{loading ? "Routing..." : "Get route"}</button></form>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}{route && line && <><div className="mt-5 flex gap-5 text-sm font-semibold"><span>{(route.distanceMeters / 1000).toFixed(1)} km</span><span>{Math.round(route.durationSeconds / 60)} min</span><span className="text-[var(--muted)]">via {route.provider}</span></div><div className="mt-4 h-[280px] overflow-hidden rounded-2xl"><MapContainer center={line[0]} zoom={12} scrollWheelZoom className="h-full w-full"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Polyline positions={line} pathOptions={{ color: "#0f766e", weight: 5 }} /></MapContainer></div></>}</section>;
}
