ALTER TABLE "CuratedPlace" ADD COLUMN "importanceScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CuratedPlace" ADD COLUMN "completenessScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CuratedPlace" ADD COLUMN "geographicScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CuratedPlace" ADD COLUMN "diversityScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CuratedPlace" ADD COLUMN "totalScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CuratedPlace" ADD COLUMN "tier" TEXT NOT NULL DEFAULT 'TIER_3';
ALTER TABLE "CuratedPlace" ADD COLUMN "curationVersion" TEXT NOT NULL DEFAULT 'legacy';
