"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { DashboardOverview, getDashboardOverview } from "@/lib/api";

export default function DashboardPage() {
  const [data, setData] = useState<DashboardOverview | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { getDashboardOverview().then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "Dashboard unavailable")); }, []);
  if (error) return <main className="min-h-screen bg-[var(--background)] px-6 pb-20 pt-32"><section className="mx-auto max-w-7xl"><h1 className="text-4xl font-black text-[var(--foreground)]">Dashboard</h1><p className="mt-4 text-[var(--muted)]">{error}. Administrator access is required.</p></section></main>;
  if (!data) return <main className="min-h-screen bg-[var(--background)] px-6 pb-20 pt-32"><section className="mx-auto max-w-7xl"><p className="text-[var(--muted)]">Loading dashboard...</p></section></main>;
  const cards = [["Cities", data.totals.cities], ["Production places", data.totals.places], ["Users", data.totals.users], ["Reviews", data.totals.reviews], ["Ratings", data.totals.ratings], ["Images", data.totals.images]];
  return <main className="min-h-screen bg-[var(--background)] px-6 pb-20 pt-32"><section className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[var(--primary)]">CityVerse analytics</p><h1 className="mt-3 text-4xl font-black text-[var(--foreground)]">Global dashboard</h1><p className="mt-4 text-[var(--muted)]">Read-only aggregates from the production CityVerse dataset.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label, value]) => <div key={label} className="rounded-3xl border border-[var(--border)] bg-[var(--card)] p-5"><p className="text-sm text-[var(--muted)]">{label}</p><p className="mt-2 text-3xl font-black text-[var(--foreground)]">{Number(value).toLocaleString()}</p></div>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-[var(--border)] bg-[var(--card)] p-6"><h2 className="text-xl font-black text-[var(--foreground)]">Places by category</h2><div className="mt-5 space-y-3">{data.categories.map((item) => <div key={item.category} className="flex items-center justify-between text-sm"><span className="capitalize text-[var(--foreground)]">{item.category.replaceAll("_", " ")}</span><span className="font-bold text-[var(--primary)]">{item.count.toLocaleString()}</span></div>)}</div></section><section className="rounded-3xl border border-[var(--border)] bg-[var(--card)] p-6"><h2 className="text-xl font-black text-[var(--foreground)]">City coverage</h2><div className="mt-5 space-y-3">{data.cities.map((city) => <Link key={city.id} href={`/dashboard/cities/${city.id}`} className="flex items-center justify-between rounded-2xl border border-[var(--border)] p-3 text-sm hover:border-[var(--primary)]"><span className="text-[var(--foreground)]">{city.name}, {city.country}</span><span className="font-bold text-[var(--primary)]">{city.placeCount.toLocaleString()}</span></Link>)}</div></section></div></section></main>;
}
